### ISSUE TITLE
Blue and Black toolpath colors

### ISSUE THREAD

**Issue by Scott216** [vlachoudis/bCNC#66]
When I opened a gcode file, some of the toolpaths are black and some are blue.  What's the difference?
![bcnc screenshot 150604a](https://cloud.githubusercontent.com/assets/819693/7995296/a21e1d3a-0ae2-11e5-93e4-805fc68d20bd.JPG)

**Comment by vlachoudis** [comment]
Blue are the selected ones. You can (un)select with the mouse clicking or dragging in the canvas or from the editor. Esc will unselect everything. Once you select you can process/modify the paths eg manually edit them, delete them, exclude them from sending, translate rotate, profile, and many other.

**Comment by Effer** [comment]
On file opening nothing should be selected. But this is not working correctly. Also if you select some path and open another gcode file, the new part programm present some path already selected.
@vlachoudis  on an old pull request I've made a small fix to unselectAll on loadGcode in bCNC.py Maybe is gonna lost?

**Comment by vlachoudis** [comment]
@Effer I don't remember this pull request. I will fix it now on the master stream.

**Comment by vlachoudis** [comment]
Now it should be fixed

**Comment by Effer** [comment]
It works better.Thanks.
Unfortunately still there are some defects on fit2screen after loading the file, especially if you open with path already selected. The gcode is not fitted, neither using the button. The only way to make it work again, is to zoom out a few time and then fit2screen.

**Comment by vlachoudis** [comment]
@Scott216 @Effer is this issue still valid?

**Comment by Effer** [comment]
Hi @vlachoudis, is still present the problem with fit2screen:
some time the calculation for adjust the screen view to fit the gcode give bad result. Mainly the zoom factor is correct but the offset for the scroll bar are not. I gave a look to the code but with poor results.

**Comment by Effer** [comment]
@vlachoudis do you fix it? Fit2screen now seems to work. 
It was something related to the scroll bars of the canvas?

**Comment by vlachoudis** [comment]
I corrected a few things but I didn't find the exact cause of it. It has to do something with the canvas widget of tkinter. 
I saw that sometimes the polylines are cropped if I don't draw the axes before. I believe that in some combinations the max limits of the canvas are not updated and then fit2screen doesn't work as well the zoom out.

**Comment by Effer** [comment]
Anyway it works much better now.
